name: CD

on:
  workflow_dispatch: {}
  push:
    tags: [ 'v*.*.*' ]

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.1'

    - name: Build
      run: |
        make -j bin/vnc-ws-gateway.{amd64,arm64}.static
        for arch in amd64 arm64; do
          mv bin/vnc-ws-gateway.$arch{.static,}
        done

    - uses: ncipollo/release-action@v1
      with:
        artifacts: "bin/vnc-ws-gateway.*"
